<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Data-Preprocessing" data-toc-modified-id="Data-Preprocessing-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Data Preprocessing</a></span></li><li><span><a href="#Scaling-of-values" data-toc-modified-id="Scaling-of-values-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Scaling of values</a></span></li><li><span><a href="#Data-Visualization" data-toc-modified-id="Data-Visualization-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Data Visualization</a></span></li><li><span><a href="#Neural-network" data-toc-modified-id="Neural-network-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Neural network</a></span><ul class="toc-item"><li><span><a href="#Model---1" data-toc-modified-id="Model---1-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Model - 1</a></span><ul class="toc-item"><li><span><a href="#Batch-size-=-6" data-toc-modified-id="Batch-size-=-6-4.1.1"><span class="toc-item-num">4.1.1&nbsp;&nbsp;</span>Batch size = 6</a></span></li><li><span><a href="#Batch-size-=-2" data-toc-modified-id="Batch-size-=-2-4.1.2"><span class="toc-item-num">4.1.2&nbsp;&nbsp;</span>Batch size = 2</a></span></li></ul></li><li><span><a href="#Model---2" data-toc-modified-id="Model---2-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Model - 2</a></span><ul class="toc-item"><li><span><a href="#Batch-size-=-6" data-toc-modified-id="Batch-size-=-6-4.2.1"><span class="toc-item-num">4.2.1&nbsp;&nbsp;</span>Batch size = 6</a></span></li><li><span><a href="#Batch-size-=-2" data-toc-modified-id="Batch-size-=-2-4.2.2"><span class="toc-item-num">4.2.2&nbsp;&nbsp;</span>Batch size = 2</a></span></li></ul></li><li><span><a href="#Model---3" data-toc-modified-id="Model---3-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Model - 3</a></span><ul class="toc-item"><li><span><a href="#Batch-size-=-6" data-toc-modified-id="Batch-size-=-6-4.3.1"><span class="toc-item-num">4.3.1&nbsp;&nbsp;</span>Batch size = 6</a></span></li><li><span><a href="#Batch-size-=-2" data-toc-modified-id="Batch-size-=-2-4.3.2"><span class="toc-item-num">4.3.2&nbsp;&nbsp;</span>Batch size = 2</a></span></li></ul></li><li><span><a href="#Model---4" data-toc-modified-id="Model---4-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>Model - 4</a></span><ul class="toc-item"><li><span><a href="#Batch-size-=-6" data-toc-modified-id="Batch-size-=-6-4.4.1"><span class="toc-item-num">4.4.1&nbsp;&nbsp;</span>Batch size = 6</a></span></li><li><span><a href="#Batch-size-=-2" data-toc-modified-id="Batch-size-=-2-4.4.2"><span class="toc-item-num">4.4.2&nbsp;&nbsp;</span>Batch size = 2</a></span></li></ul></li><li><span><a href="#Model---5" data-toc-modified-id="Model---5-4.5"><span class="toc-item-num">4.5&nbsp;&nbsp;</span>Model - 5</a></span><ul class="toc-item"><li><span><a href="#Batch-size-=-6" data-toc-modified-id="Batch-size-=-6-4.5.1"><span class="toc-item-num">4.5.1&nbsp;&nbsp;</span>Batch size = 6</a></span></li><li><span><a href="#Batch-size-=-2" data-toc-modified-id="Batch-size-=-2-4.5.2"><span class="toc-item-num">4.5.2&nbsp;&nbsp;</span>Batch size = 2</a></span></li></ul></li><li><span><a href="#Model---6" data-toc-modified-id="Model---6-4.6"><span class="toc-item-num">4.6&nbsp;&nbsp;</span>Model - 6</a></span><ul class="toc-item"><li><span><a href="#Batch-size-=-6" data-toc-modified-id="Batch-size-=-6-4.6.1"><span class="toc-item-num">4.6.1&nbsp;&nbsp;</span>Batch size = 6</a></span></li><li><span><a href="#Batch-size-=-2" data-toc-modified-id="Batch-size-=-2-4.6.2"><span class="toc-item-num">4.6.2&nbsp;&nbsp;</span>Batch size = 2</a></span></li></ul></li></ul></li></ul></div>

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
import cv2 as cv
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.preprocessing import PolynomialFeatures
import pydicom
from sklearn.metrics import roc_auc_score
from copy import deepcopy
from sklearn.utils import shuffle
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
import tensorflow as tf
import seaborn as sns
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'
from statistics import mode
from tensorflow.keras.losses import MeanSquaredError
tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)

# Data Preprocessing

In [2]:
df = pd.read_csv('/Users/rt/Desktop/College/Cancer Project/data/dataset_training.csv')

In [3]:
y = df['Status']
df.drop(columns = ['Patient', 'Slice no', 'Distance', 'Status', 'Unnamed: 0'], inplace = True)

In [4]:
display(df)

ASM    Energy      Contrast  Dissimilarity  Homogeneity  \
0    0.000338  0.018383  22619.771613      37.636084     0.261268   
1    0.000374  0.019349  20177.119559      33.165612     0.264537   
2    0.000157  0.012512  44325.511746      66.719744     0.147493   
3    0.000181  0.013460  40997.628612      60.512876     0.152135   
4    0.000110  0.010486  64881.503529      92.002059     0.091236   
..        ...       ...           ...            ...          ...   
847  0.000364  0.019091  12266.695245      24.687676     0.253209   
848  0.000188  0.013713  25487.729027      44.233550     0.159562   
849  0.000184  0.013560  24857.645301      43.017171     0.153731   
850  0.000126  0.011216  38412.296961      61.690736     0.103327   
851  0.000133  0.011537  37212.159995      59.164450     0.108169   

     Correlation   Entropy  
0       0.534480  7.821678  
1       0.545926  7.780412  
2       0.452187  7.821678  
3       0.449952  7.780412  
4       0.391190  7.821678  
..           ...       ...  
847     0.579264  7.681438  
848     0.456916  7.741331  
849     0.453286  7.681438  
850     0.373230  7.741331  
851     0.375185  7.681438  

[852 rows x 7 columns]

In [5]:
df.describe()

ASM      Energy       Contrast  Dissimilarity  Homogeneity  \
count  852.000000  852.000000     852.000000     852.000000   852.000000   
mean     0.000248    0.015288   48113.285046      66.311519     0.172208   
std      0.000126    0.003772   23896.556196      27.734403     0.073132   
min      0.000077    0.008753   10889.068825      22.273004     0.075971   
25%      0.000149    0.012198   26689.370174      41.561096     0.106078   
50%      0.000202    0.014228   44506.430494      64.532099     0.148011   
75%      0.000337    0.018362   65249.733383      86.785928     0.244715   
max      0.000898    0.029972  117996.688595     141.256488     0.339512   

       Correlation     Entropy  
count   852.000000  852.000000  
mean      0.440122    7.801223  
std       0.074135    0.125318  
min       0.247521    7.543274  
25%       0.384820    7.707459  
50%       0.438384    7.776155  
75%       0.494098    7.874459  
max       0.617244    8.177869

# Scaling of values

In [6]:
cols = df.columns
scalar = StandardScaler()
temp = scalar.fit_transform(df)
df = pd.DataFrame(temp, columns = cols)

In [7]:
display(df)

ASM    Energy  Contrast  Dissimilarity  Homogeneity  Correlation  \
0    0.716075  0.821015 -1.067455      -1.034537     1.218506     1.273524   
1    1.006127  1.077312 -1.169732      -1.195821     1.263238     1.428001   
2   -0.726990 -0.736279 -0.158600       0.014728    -0.338159     0.162826   
3   -0.531240 -0.484990 -0.297944      -0.209200    -0.274644     0.132663   
4   -1.097862 -1.273945  0.702112       0.926850    -1.107864    -0.660435   
..        ...       ...       ...            ...          ...          ...   
847  0.927127  1.008791 -1.500955      -1.501683     1.108242     1.877954   
848 -0.476488 -0.417810 -0.947369      -0.796518    -0.173023     0.226653   
849 -0.509667 -0.458371 -0.973751      -0.840401    -0.252805     0.177671   
850 -0.971796 -1.080261 -0.406196      -0.166706    -0.942432    -0.902834   
851 -0.913709 -0.995142 -0.456448      -0.257848    -0.876181    -0.876449   

      Entropy  
0    0.163317  
1   -0.166163  
2    0.163317  
3   -0.166163  
4    0.163317  
..        ...  
847 -0.956408  
848 -0.478205  
849 -0.956408  
850 -0.478205  
851 -0.956408  

[852 rows x 7 columns]

# Data Visualization

In [8]:
'''temp = df.columns.values.tolist()
for i in temp:
    x = df[i]
    plt.scatter(x, y)
    plt.xlabel(i)
    plt.ylabel('Cancer presence')
    plt.title('%s vs Cancer presence'%i)
    plt.show()'''

"temp = df.columns.values.tolist()\nfor i in temp:\n    x = df[i]\n    plt.scatter(x, y)\n    plt.xlabel(i)\n    plt.ylabel('Cancer presence')\n    plt.title('%s vs Cancer presence'%i)\n    plt.show()"

In [9]:
#sns.pairplot(df)

In [10]:
def performance_metrics(y_test, y_pred):
    print('Performance metrics:')
    print(classification_report(y_test, y_pred), '\n')
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred),'\n')
    tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
    print('True positive: ', tp)
    print('True negavtive: ', tn)
    print('False positive: ', fp)
    print('False negative: ', fn)

In [11]:
x_train, x_test, y_train, y_test = train_test_split(df, y, 
                                                    test_size=0.3, 
                                                    random_state=0)

# Neural network

## Model - 1

### Batch size = 6

In [12]:
classifier1 = Sequential([
    Dense(7, activation = 'relu', kernel_initializer = 'random_normal', input_dim = 7),
    Dense(6, activation = 'relu', kernel_initializer = 'random_normal'),
    Dense(1, activation = 'sigmoid', kernel_initializer = 'random_normal')
])

In [13]:
classifier1.compile(optimizer = 'adam',
                   loss = 'binary_crossentropy',
                   metrics = ['accuracy'],
                   )

In [14]:
classifier1.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 7)                 56        
_________________________________________________________________
dense_1 (Dense)              (None, 6)                 48        
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 7         
Total params: 111
Trainable params: 111
Non-trainable params: 0
_________________________________________________________________


In [15]:
classifier1.fit(x_train, y_train, batch_size = 6, epochs = 100, verbose = 0)

In [16]:
print(f'Accuracy on training set : {classifier1.evaluate(x_train, y_train)[1]} \n')
print(f'Loss on training set : {classifier1.evaluate(x_train, y_train)[0]}')

596/596 [==============================] - 0s 727us/sample - loss: 0.5645 - accuracy: 0.7282
Accuracy on training set : 0.7281879186630249 

596/596 [==============================] - 0s 77us/sample - loss: 0.5645 - accuracy: 0.7282
Loss on training set : 0.5644667124588217


In [17]:
y_pred = classifier1.predict_classes(x_train)
performance_metrics(y_train, y_pred)

Performance metrics:
              precision    recall  f1-score   support

         0.0       0.74      0.73      0.73       306
         1.0       0.72      0.72      0.72       290

    accuracy                           0.73       596
   macro avg       0.73      0.73      0.73       596
weighted avg       0.73      0.73      0.73       596
 

Confusion Matrix:
[[224  82]
 [ 80 210]] 

True positive:  210
True negavtive:  224
False positive:  82
False negative:  80


In [18]:
print(f'Accuracy on testing set : {classifier1.evaluate(x_test, y_test)[1]} \n')
print(f'Loss on testing set : {classifier1.evaluate(x_test, y_test)[0]}')

256/256 [==============================] - 0s 89us/sample - loss: 0.5698 - accuracy: 0.7344
Accuracy on testing set : 0.734375 

256/256 [==============================] - 0s 86us/sample - loss: 0.5698 - accuracy: 0.7344
Loss on testing set : 0.5697931051254272


In [19]:
y_pred = classifier1.predict_classes(x_test)
performance_metrics(y_test, y_pred)

Performance metrics:
              precision    recall  f1-score   support

         0.0       0.71      0.74      0.72       120
         1.0       0.76      0.73      0.74       136

    accuracy                           0.73       256
   macro avg       0.73      0.73      0.73       256
weighted avg       0.74      0.73      0.73       256
 

Confusion Matrix:
[[89 31]
 [37 99]] 

True positive:  99
True negavtive:  89
False positive:  31
False negative:  37


### Batch size = 2

In [20]:
classifier1.fit(x_train, y_train, batch_size = 2, epochs = 100, verbose = 0)

In [21]:
print(f'Accuracy on training set : {classifier1.evaluate(x_train, y_train)[1]} \n')
print(f'Loss on training set : {classifier1.evaluate(x_train, y_train)[0]}')

596/596 [==============================] - 0s 54us/sample - loss: 0.4622 - accuracy: 0.7567
Accuracy on training set : 0.7567114233970642 

596/596 [==============================] - 0s 55us/sample - loss: 0.4622 - accuracy: 0.7567
Loss on training set : 0.46222219851193014


In [22]:
y_pred = classifier1.predict_classes(x_train)
performance_metrics(y_train, y_pred)

Performance metrics:
              precision    recall  f1-score   support

         0.0       0.74      0.80      0.77       306
         1.0       0.77      0.71      0.74       290

    accuracy                           0.76       596
   macro avg       0.76      0.76      0.76       596
weighted avg       0.76      0.76      0.76       596
 

Confusion Matrix:
[[246  60]
 [ 85 205]] 

True positive:  205
True negavtive:  246
False positive:  60
False negative:  85


In [23]:
print(f'Accuracy on testing set : {classifier1.evaluate(x_test, y_test)[1]} \n')
print(f'Loss on testing set : {classifier1.evaluate(x_test, y_test)[0]}')

256/256 [==============================] - 0s 97us/sample - loss: 0.4897 - accuracy: 0.7500
Accuracy on testing set : 0.75 

256/256 [==============================] - 0s 94us/sample - loss: 0.4897 - accuracy: 0.7500
Loss on testing set : 0.48970238864421844


In [24]:
y_pred = classifier1.predict_classes(x_test)
performance_metrics(y_test, y_pred)

Performance metrics:
              precision    recall  f1-score   support

         0.0       0.69      0.85      0.76       120
         1.0       0.83      0.66      0.74       136

    accuracy                           0.75       256
   macro avg       0.76      0.76      0.75       256
weighted avg       0.77      0.75      0.75       256
 

Confusion Matrix:
[[102  18]
 [ 46  90]] 

True positive:  90
True negavtive:  102
False positive:  18
False negative:  46


## Model - 2

### Batch size = 6

In [25]:
classifier2 = Sequential([
    Dense(7, activation = 'relu', kernel_initializer = 'random_normal', input_dim = 7),
    Dense(128, activation = 'relu', kernel_initializer = 'random_normal'),
    Dense(1, activation = 'sigmoid',kernel_initializer = 'random_normal')
])

In [26]:
classifier2.compile(optimizer = 'adam', 
                    loss = 'binary_crossentropy', 
                    metrics = ['accuracy'])

In [27]:
classifier2.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 7)                 56        
_________________________________________________________________
dense_4 (Dense)              (None, 128)               1024      
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 129       
Total params: 1,209
Trainable params: 1,209
Non-trainable params: 0
_________________________________________________________________


In [28]:
classifier2.fit(x_train, y_train, batch_size = 6, epochs = 100, verbose = 0)

In [29]:
print(f'Accuracy on training set : {classifier2.evaluate(x_train, y_train)[1]} \n')
print(f'Loss on training set : {classifier2.evaluate(x_train, y_train)[0]}')

596/596 [==============================] - 0s 792us/sample - loss: 0.4295 - accuracy: 0.8104
Accuracy on training set : 0.8104026913642883 

596/596 [==============================] - 0s 88us/sample - loss: 0.4295 - accuracy: 0.8104
Loss on training set : 0.42948017704406843


In [30]:
y_pred = classifier2.predict_classes(x_train)
performance_metrics(y_train, y_pred)

Performance metrics:
              precision    recall  f1-score   support

         0.0       0.82      0.80      0.81       306
         1.0       0.80      0.82      0.81       290

    accuracy                           0.81       596
   macro avg       0.81      0.81      0.81       596
weighted avg       0.81      0.81      0.81       596
 

Confusion Matrix:
[[246  60]
 [ 53 237]] 

True positive:  237
True negavtive:  246
False positive:  60
False negative:  53


In [31]:
print(f'Accuracy on testing set : {classifier2.evaluate(x_test, y_test)[1]} \n')
print(f'Loss on testing set : {classifier2.evaluate(x_test, y_test)[0]}')

256/256 [==============================] - 0s 106us/sample - loss: 0.4880 - accuracy: 0.7734
Accuracy on testing set : 0.7734375 

256/256 [==============================] - 0s 101us/sample - loss: 0.4880 - accuracy: 0.7734
Loss on testing set : 0.4880234897136688


In [32]:
y_pred = classifier2.predict_classes(x_test)
performance_metrics(y_test, y_pred)

Performance metrics:
              precision    recall  f1-score   support

         0.0       0.75      0.77      0.76       120
         1.0       0.79      0.78      0.79       136

    accuracy                           0.77       256
   macro avg       0.77      0.77      0.77       256
weighted avg       0.77      0.77      0.77       256
 

Confusion Matrix:
[[ 92  28]
 [ 30 106]] 

True positive:  106
True negavtive:  92
False positive:  28
False negative:  30


### Batch size = 2

In [33]:
classifier2.fit(x_train, y_train, batch_size = 2, epochs = 100, verbose = 0)

In [34]:
print(f'Accuracy on training set : {classifier2.evaluate(x_train, y_train)[1]} \n')
print(f'Loss on training set : {classifier2.evaluate(x_train, y_train)[0]}')
y_pred = classifier2.predict_classes(x_train)
performance_metrics(y_train, y_pred)

596/596 [==============================] - 0s 51us/sample - loss: 0.2912 - accuracy: 0.8775
Accuracy on training set : 0.8775168061256409 

596/596 [==============================] - 0s 82us/sample - loss: 0.2912 - accuracy: 0.8775
Loss on training set : 0.2911587239511861
Performance metrics:
              precision    recall  f1-score   support

         0.0       0.87      0.89      0.88       306
         1.0       0.88      0.87      0.87       290

    accuracy                           0.88       596
   macro avg       0.88      0.88      0.88       596
weighted avg       0.88      0.88      0.88       596
 

Confusion Matrix:
[[272  34]
 [ 39 251]] 

True positive:  251
True negavtive:  272
False positive:  34
False negative:  39


In [35]:
print(f'Accuracy on testing set : {classifier2.evaluate(x_test, y_test)[1]} \n')
print(f'Loss on testing set : {classifier2.evaluate(x_test, y_test)[0]}')
y_pred = classifier2.predict_classes(x_test)
performance_metrics(y_test, y_pred)

256/256 [==============================] - 0s 99us/sample - loss: 0.4296 - accuracy: 0.7852
Accuracy on testing set : 0.78515625 

256/256 [==============================] - 0s 127us/sample - loss: 0.4296 - accuracy: 0.7852
Loss on testing set : 0.42963801324367523
Performance metrics:
              precision    recall  f1-score   support

         0.0       0.75      0.82      0.78       120
         1.0       0.82      0.76      0.79       136

    accuracy                           0.79       256
   macro avg       0.79      0.79      0.79       256
weighted avg       0.79      0.79      0.79       256
 

Confusion Matrix:
[[ 98  22]
 [ 33 103]] 

True positive:  103
True negavtive:  98
False positive:  22
False negative:  33


## Model - 3

### Batch size = 6

In [36]:
classifier3 = Sequential([
    Dense(7, activation = 'relu', kernel_initializer = 'random_normal', input_dim = 7),
    Dense(128, activation = 'relu', kernel_initializer = 'random_normal'),
    Dense(256, activation = 'relu', kernel_initializer = 'random_normal'),
    Dense(1, activation = 'sigmoid',kernel_initializer = 'random_normal')
])

In [37]:
classifier3.compile(optimizer = 'adam', 
                    loss = 'binary_crossentropy', 
                    metrics = ['accuracy'])

In [38]:
classifier3.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 7)                 56        
_________________________________________________________________
dense_7 (Dense)              (None, 128)               1024      
_________________________________________________________________
dense_8 (Dense)              (None, 256)               33024     
_________________________________________________________________
dense_9 (Dense)              (None, 1)                 257       
Total params: 34,361
Trainable params: 34,361
Non-trainable params: 0
_________________________________________________________________


In [40]:
classifier3.fit(x_train, y_train, epochs = 100, batch_size = 6, verbose = 0)

In [41]:
print(f'Accuracy on training set : {classifier3.evaluate(x_train, y_train)[1]} \n')
print(f'Loss on training set : {classifier3.evaluate(x_train, y_train)[0]}')
y_pred = classifier3.predict_classes(x_train)
performance_metrics(y_train, y_pred)

596/596 [==============================] - 0s 777us/sample - loss: 0.1540 - accuracy: 0.9295
Accuracy on training set : 0.9295302033424377 

596/596 [==============================] - 0s 167us/sample - loss: 0.1540 - accuracy: 0.9295
Loss on training set : 0.15400686240036215
Performance metrics:
              precision    recall  f1-score   support

         0.0       0.89      0.99      0.93       306
         1.0       0.98      0.87      0.92       290

    accuracy                           0.93       596
   macro avg       0.94      0.93      0.93       596
weighted avg       0.94      0.93      0.93       596
 

Confusion Matrix:
[[302   4]
 [ 38 252]] 

True positive:  252
True negavtive:  302
False positive:  4
False negative:  38


In [42]:
print(f'Accuracy on testing set : {classifier3.evaluate(x_test, y_test)[1]} \n')
print(f'Loss on testing set : {classifier3.evaluate(x_test, y_test)[0]}')
y_pred = classifier3.predict_classes(x_test)
performance_metrics(y_test, y_pred)

256/256 [==============================] - 0s 147us/sample - loss: 0.3908 - accuracy: 0.8477
Accuracy on testing set : 0.84765625 

256/256 [==============================] - 0s 177us/sample - loss: 0.3908 - accuracy: 0.8477
Loss on testing set : 0.39079091884195805
Performance metrics:
              precision    recall  f1-score   support

         0.0       0.80      0.89      0.85       120
         1.0       0.89      0.81      0.85       136

    accuracy                           0.85       256
   macro avg       0.85      0.85      0.85       256
weighted avg       0.85      0.85      0.85       256
 

Confusion Matrix:
[[107  13]
 [ 26 110]] 

True positive:  110
True negavtive:  107
False positive:  13
False negative:  26


### Batch size = 2

In [43]:
classifier3.fit(x_train, y_train, epochs = 100, batch_size = 2, verbose = 0)

In [44]:
print(f'Accuracy on training set : {classifier3.evaluate(x_train, y_train)[1]} \n')
print(f'Loss on training set : {classifier3.evaluate(x_train, y_train)[0]}')
y_pred = classifier3.predict_classes(x_train)
performance_metrics(y_train, y_pred)

596/596 [==============================] - 0s 122us/sample - loss: 0.1512 - accuracy: 0.9362
Accuracy on training set : 0.936241626739502 

596/596 [==============================] - 0s 125us/sample - loss: 0.1512 - accuracy: 0.9362
Loss on training set : 0.15120542114413024
Performance metrics:
              precision    recall  f1-score   support

         0.0       0.98      0.90      0.94       306
         1.0       0.90      0.98      0.94       290

    accuracy                           0.94       596
   macro avg       0.94      0.94      0.94       596
weighted avg       0.94      0.94      0.94       596
 

Confusion Matrix:
[[274  32]
 [  6 284]] 

True positive:  284
True negavtive:  274
False positive:  32
False negative:  6


In [45]:
print(f'Accuracy on testing set : {classifier3.evaluate(x_test, y_test)[1]} \n')
print(f'Loss on testing set : {classifier3.evaluate(x_test, y_test)[0]}')
y_pred = classifier3.predict_classes(x_test)
performance_metrics(y_test, y_pred)

256/256 [==============================] - 0s 143us/sample - loss: 0.4499 - accuracy: 0.8594
Accuracy on testing set : 0.859375 

256/256 [==============================] - 0s 118us/sample - loss: 0.4499 - accuracy: 0.8594
Loss on testing set : 0.44986957125365734
Performance metrics:
              precision    recall  f1-score   support

         0.0       0.89      0.80      0.84       120
         1.0       0.84      0.91      0.87       136

    accuracy                           0.86       256
   macro avg       0.86      0.86      0.86       256
weighted avg       0.86      0.86      0.86       256
 

Confusion Matrix:
[[ 96  24]
 [ 12 124]] 

True positive:  124
True negavtive:  96
False positive:  24
False negative:  12


## Model - 4

### Batch size = 6

In [46]:
classifier4 = Sequential([
    Dense(7, activation = 'relu', kernel_initializer = 'random_normal', input_dim = 7),
    Dense(256, activation = 'relu', kernel_initializer = 'random_normal'),
    Dense(512, activation = 'relu', kernel_initializer = 'random_normal'),
    Dense(1, activation = 'sigmoid',kernel_initializer = 'random_normal')
])

In [47]:
classifier4.compile(optimizer = 'adam', 
                    loss = 'binary_crossentropy', 
                    metrics = ['accuracy'])

In [48]:
classifier4.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_10 (Dense)             (None, 7)                 56        
_________________________________________________________________
dense_11 (Dense)             (None, 256)               2048      
_________________________________________________________________
dense_12 (Dense)             (None, 512)               131584    
_________________________________________________________________
dense_13 (Dense)             (None, 1)                 513       
Total params: 134,201
Trainable params: 134,201
Non-trainable params: 0
_________________________________________________________________


In [49]:
classifier4.fit(x_train, y_train, epochs = 100, batch_size = 6, verbose = 0)

In [50]:
print(f'Accuracy on training set : {classifier4.evaluate(x_train, y_train)[1]} \n')
print(f'Loss on training set : {classifier4.evaluate(x_train, y_train)[0]}')
y_pred = classifier4.predict_classes(x_train)
performance_metrics(y_train, y_pred)

596/596 [==============================] - 0s 682us/sample - loss: 0.2786 - accuracy: 0.8758
Accuracy on training set : 0.8758389353752136 

596/596 [==============================] - 0s 154us/sample - loss: 0.2786 - accuracy: 0.8758
Loss on training set : 0.2785890198393956
Performance metrics:
              precision    recall  f1-score   support

         0.0       0.83      0.96      0.89       306
         1.0       0.95      0.79      0.86       290

    accuracy                           0.88       596
   macro avg       0.89      0.87      0.87       596
weighted avg       0.89      0.88      0.87       596
 

Confusion Matrix:
[[294  12]
 [ 62 228]] 

True positive:  228
True negavtive:  294
False positive:  12
False negative:  62


In [51]:
print(f'Accuracy on testing set : {classifier4.evaluate(x_test, y_test)[1]} \n')
print(f'Loss on testing set : {classifier4.evaluate(x_test, y_test)[0]}')
y_pred = classifier4.predict_classes(x_test)
performance_metrics(y_test, y_pred)

256/256 [==============================] - 0s 129us/sample - loss: 0.4211 - accuracy: 0.7969
Accuracy on testing set : 0.796875 

256/256 [==============================] - 0s 160us/sample - loss: 0.4211 - accuracy: 0.7969
Loss on testing set : 0.4210826978087425
Performance metrics:
              precision    recall  f1-score   support

         0.0       0.72      0.94      0.81       120
         1.0       0.93      0.67      0.78       136

    accuracy                           0.80       256
   macro avg       0.82      0.81      0.80       256
weighted avg       0.83      0.80      0.79       256
 

Confusion Matrix:
[[113   7]
 [ 45  91]] 

True positive:  91
True negavtive:  113
False positive:  7
False negative:  45


### Batch size = 2

In [52]:
classifier4.fit(x_train, y_train, epochs = 100, batch_size = 2, verbose = 0)

In [53]:
print(f'Accuracy on training set : {classifier4.evaluate(x_train, y_train)[1]} \n')
print(f'Loss on training set : {classifier4.evaluate(x_train, y_train)[0]}')
y_pred = classifier4.predict_classes(x_train)
performance_metrics(y_train, y_pred)

596/596 [==============================] - 0s 173us/sample - loss: 0.1526 - accuracy: 0.9228
Accuracy on training set : 0.9228187799453735 

596/596 [==============================] - 0s 162us/sample - loss: 0.1526 - accuracy: 0.9228
Loss on training set : 0.15261986436659858
Performance metrics:
              precision    recall  f1-score   support

         0.0       0.95      0.89      0.92       306
         1.0       0.89      0.96      0.92       290

    accuracy                           0.92       596
   macro avg       0.92      0.92      0.92       596
weighted avg       0.92      0.92      0.92       596
 

Confusion Matrix:
[[273  33]
 [ 13 277]] 

True positive:  277
True negavtive:  273
False positive:  33
False negative:  13


In [73]:
print(f'Accuracy on testing set : {classifier4.evaluate(x_test, y_test)[1]} \n')
print(f'Loss on testing set : {classifier4.evaluate(x_test, y_test)[0]}')
y_pred = classifier4.predict_classes(x_test)
performance_metrics(y_test, y_pred)

256/256 [==============================] - 0s 199us/sample - loss: 0.5423 - accuracy: 0.8438
Accuracy on testing set : 0.84375 

256/256 [==============================] - 0s 52us/sample - loss: 0.5423 - accuracy: 0.8438
Loss on testing set : 0.5423131808638573
Performance metrics:
              precision    recall  f1-score   support

         0.0       0.84      0.82      0.83       120
         1.0       0.84      0.87      0.86       136

    accuracy                           0.84       256
   macro avg       0.84      0.84      0.84       256
weighted avg       0.84      0.84      0.84       256
 

Confusion Matrix:
[[ 98  22]
 [ 18 118]] 

True positive:  118
True negavtive:  98
False positive:  22
False negative:  18


## Model - 5

### Batch size = 6

In [55]:
classifier5 = Sequential([
    Dense(7, activation = 'relu', kernel_initializer = 'random_normal', input_dim = 7),
    Dense(256, activation = 'relu', kernel_initializer = 'random_normal'),
    Dense(512, activation = 'relu', kernel_initializer = 'random_normal'),
    Dense(1024, activation = 'relu', kernel_initializer = 'random_normal'),
    Dense(1, activation = 'sigmoid',kernel_initializer = 'random_normal')
])

In [56]:
classifier5.compile(optimizer = 'adam', 
                    loss = 'binary_crossentropy',
                    metrics = ['accuracy'])

In [57]:
classifier5.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_14 (Dense)             (None, 7)                 56        
_________________________________________________________________
dense_15 (Dense)             (None, 256)               2048      
_________________________________________________________________
dense_16 (Dense)             (None, 512)               131584    
_________________________________________________________________
dense_17 (Dense)             (None, 1024)              525312    
_________________________________________________________________
dense_18 (Dense)             (None, 1)                 1025      
Total params: 660,025
Trainable params: 660,025
Non-trainable params: 0
_________________________________________________________________


In [58]:
classifier5.fit(x_train, y_train, epochs = 100, batch_size = 6, verbose = 0)

In [59]:
print(f'Accuracy on training set : {classifier5.evaluate(x_train, y_train)[1]} \n')
print(f'Loss on training set : {classifier5.evaluate(x_train, y_train)[0]}')
y_pred = classifier5.predict_classes(x_train)
performance_metrics(y_train, y_pred)

596/596 [==============================] - 1s 911us/sample - loss: 0.1748 - accuracy: 0.9178
Accuracy on training set : 0.9177852272987366 

596/596 [==============================] - 0s 287us/sample - loss: 0.1748 - accuracy: 0.9178
Loss on training set : 0.17481990073551268
Performance metrics:
              precision    recall  f1-score   support

         0.0       0.90      0.95      0.92       306
         1.0       0.94      0.88      0.91       290

    accuracy                           0.92       596
   macro avg       0.92      0.92      0.92       596
weighted avg       0.92      0.92      0.92       596
 

Confusion Matrix:
[[291  15]
 [ 34 256]] 

True positive:  256
True negavtive:  291
False positive:  15
False negative:  34


In [60]:
print(f'Accuracy on testing set : {classifier5.evaluate(x_test, y_test)[1]} \n')
print(f'Loss on testing set : {classifier5.evaluate(x_test, y_test)[0]}')
y_pred = classifier5.predict_classes(x_test)
performance_metrics(y_test, y_pred)

256/256 [==============================] - 0s 314us/sample - loss: 0.6686 - accuracy: 0.8008
Accuracy on testing set : 0.80078125 

256/256 [==============================] - 0s 301us/sample - loss: 0.6686 - accuracy: 0.8008
Loss on testing set : 0.6686283722519875
Performance metrics:
              precision    recall  f1-score   support

         0.0       0.76      0.85      0.80       120
         1.0       0.85      0.76      0.80       136

    accuracy                           0.80       256
   macro avg       0.80      0.80      0.80       256
weighted avg       0.81      0.80      0.80       256
 

Confusion Matrix:
[[102  18]
 [ 33 103]] 

True positive:  103
True negavtive:  102
False positive:  18
False negative:  33


### Batch size = 2

In [61]:
classifier5.fit(x_train, y_train, epochs = 100, batch_size = 2, verbose = 0)

In [62]:
print(f'Accuracy on training set : {classifier5.evaluate(x_train, y_train)[1]} \n')
print(f'Loss on training set : {classifier5.evaluate(x_train, y_train)[0]}')
y_pred = classifier5.predict_classes(x_train)
performance_metrics(y_train, y_pred)

596/596 [==============================] - 0s 277us/sample - loss: 0.1824 - accuracy: 0.9262
Accuracy on training set : 0.926174521446228 

596/596 [==============================] - 0s 252us/sample - loss: 0.1824 - accuracy: 0.9262
Loss on training set : 0.18238106875011584
Performance metrics:
              precision    recall  f1-score   support

         0.0       0.92      0.94      0.93       306
         1.0       0.94      0.91      0.92       290

    accuracy                           0.93       596
   macro avg       0.93      0.93      0.93       596
weighted avg       0.93      0.93      0.93       596
 

Confusion Matrix:
[[288  18]
 [ 26 264]] 

True positive:  264
True negavtive:  288
False positive:  18
False negative:  26


In [63]:
print(f'Accuracy on testing set : {classifier5.evaluate(x_test, y_test)[1]} \n')
print(f'Loss on testing set : {classifier5.evaluate(x_test, y_test)[0]}')
y_pred = classifier5.predict_classes(x_test)
performance_metrics(y_test, y_pred)

256/256 [==============================] - 0s 283us/sample - loss: 0.7764 - accuracy: 0.8164
Accuracy on testing set : 0.81640625 

256/256 [==============================] - 0s 226us/sample - loss: 0.7764 - accuracy: 0.8164
Loss on testing set : 0.77644944190979
Performance metrics:
              precision    recall  f1-score   support

         0.0       0.80      0.81      0.80       120
         1.0       0.83      0.82      0.83       136

    accuracy                           0.82       256
   macro avg       0.82      0.82      0.82       256
weighted avg       0.82      0.82      0.82       256
 

Confusion Matrix:
[[ 97  23]
 [ 24 112]] 

True positive:  112
True negavtive:  97
False positive:  23
False negative:  24


## Model - 6

### Batch size = 6

In [64]:
classifier6 = Sequential([
    Dense(7, activation = 'relu', kernel_initializer = 'random_normal', input_dim = 7),
    Dense(128, activation = 'relu', kernel_initializer = 'random_normal'),
    Dense(512, activation = 'relu', kernel_initializer = 'random_normal'),
    Dense(1024, activation = 'relu', kernel_initializer = 'random_normal'),
    Dense(2048, activation = 'relu', kernel_initializer = 'random_normal'),
    Dense(1, activation = 'sigmoid',kernel_initializer = 'random_normal')
])

In [65]:
classifier6.compile(optimizer = 'adam', 
                    loss = 'binary_crossentropy', 
                    metrics = ['accuracy'])

In [66]:
classifier6.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_19 (Dense)             (None, 7)                 56        
_________________________________________________________________
dense_20 (Dense)             (None, 128)               1024      
_________________________________________________________________
dense_21 (Dense)             (None, 512)               66048     
_________________________________________________________________
dense_22 (Dense)             (None, 1024)              525312    
_________________________________________________________________
dense_23 (Dense)             (None, 2048)              2099200   
_________________________________________________________________
dense_24 (Dense)             (None, 1)                 2049      
Total params: 2,693,689
Trainable params: 2,693,689
Non-trainable params: 0
____________________________________________

In [67]:
classifier6.fit(x_train, y_train, epochs = 100, batch_size = 6, verbose = 0)

In [68]:
print(f'Accuracy on training set : {classifier6.evaluate(x_train, y_train)[1]} \n')
print(f'Loss on training set : {classifier6.evaluate(x_train, y_train)[0]}')
y_pred = classifier6.predict_classes(x_train)
performance_metrics(y_train, y_pred)

596/596 [==============================] - 1s 1ms/sample - loss: 0.2329 - accuracy: 0.8859
Accuracy on training set : 0.8859060406684875 

596/596 [==============================] - 0s 354us/sample - loss: 0.2329 - accuracy: 0.8859
Loss on training set : 0.23285612283937082
Performance metrics:
              precision    recall  f1-score   support

         0.0       0.89      0.88      0.89       306
         1.0       0.88      0.89      0.88       290

    accuracy                           0.89       596
   macro avg       0.89      0.89      0.89       596
weighted avg       0.89      0.89      0.89       596
 

Confusion Matrix:
[[270  36]
 [ 32 258]] 

True positive:  258
True negavtive:  270
False positive:  36
False negative:  32


In [69]:
print(f'Accuracy on testing set : {classifier6.evaluate(x_test, y_test)[1]} \n')
print(f'Loss on testing set : {classifier6.evaluate(x_test, y_test)[0]}')
y_pred = classifier6.predict_classes(x_test)
performance_metrics(y_test, y_pred)

256/256 [==============================] - 0s 368us/sample - loss: 0.5179 - accuracy: 0.8281
Accuracy on testing set : 0.828125 

256/256 [==============================] - 0s 360us/sample - loss: 0.5179 - accuracy: 0.8281
Loss on testing set : 0.5178982801735401
Performance metrics:
              precision    recall  f1-score   support

         0.0       0.80      0.85      0.82       120
         1.0       0.86      0.81      0.83       136

    accuracy                           0.83       256
   macro avg       0.83      0.83      0.83       256
weighted avg       0.83      0.83      0.83       256
 

Confusion Matrix:
[[102  18]
 [ 26 110]] 

True positive:  110
True negavtive:  102
False positive:  18
False negative:  26


### Batch size = 2

In [70]:
classifier6.fit(x_train, y_train, epochs = 100, batch_size = 2, verbose = 0)

In [71]:
print(f'Accuracy on training set : {classifier6.evaluate(x_train, y_train)[1]} \n')
print(f'Loss on training set : {classifier6.evaluate(x_train, y_train)[0]}')
y_pred = classifier6.predict_classes(x_train)
performance_metrics(y_train, y_pred)

596/596 [==============================] - 0s 352us/sample - loss: 0.1768 - accuracy: 0.9161
Accuracy on training set : 0.9161073565483093 

596/596 [==============================] - 0s 349us/sample - loss: 0.1768 - accuracy: 0.9161
Loss on training set : 0.17676488335100596
Performance metrics:
              precision    recall  f1-score   support

         0.0       0.93      0.91      0.92       306
         1.0       0.90      0.93      0.91       290

    accuracy                           0.92       596
   macro avg       0.92      0.92      0.92       596
weighted avg       0.92      0.92      0.92       596
 

Confusion Matrix:
[[277  29]
 [ 21 269]] 

True positive:  269
True negavtive:  277
False positive:  29
False negative:  21


In [72]:
print(f'Accuracy on testing set : {classifier6.evaluate(x_test, y_test)[1]} \n')
print(f'Loss on testing set : {classifier6.evaluate(x_test, y_test)[0]}')
y_pred = classifier6.predict_classes(x_test)
performance_metrics(y_test, y_pred)

256/256 [==============================] - 0s 324us/sample - loss: 0.6495 - accuracy: 0.8008
Accuracy on testing set : 0.80078125 

256/256 [==============================] - 0s 322us/sample - loss: 0.6495 - accuracy: 0.8008
Loss on testing set : 0.6494553163647652
Performance metrics:
              precision    recall  f1-score   support

         0.0       0.79      0.78      0.79       120
         1.0       0.81      0.82      0.81       136

    accuracy                           0.80       256
   macro avg       0.80      0.80      0.80       256
weighted avg       0.80      0.80      0.80       256
 

Confusion Matrix:
[[ 94  26]
 [ 25 111]] 

True positive:  111
True negavtive:  94
False positive:  26
False negative:  25


SAMPLE TESTING!!

In [ ]:
print(f'Accuracy on SAMPLE TEST CASES : {classifier1.evaluate(df_testing, output_testing)[1]} \n')
print(f'Loss on SAMPLE TEST CASES : {classifier1.evaluate(df_testing, output_testing)[0]}')

In [ ]:
print(f'Accuracy on SAMPLE TEST CASES : {classifier2.evaluate(df_testing, output_testing)[1]} \n')
print(f'Loss on SAMPLE TEST CASES : {classifier2.evaluate(df_testing, output_testing)[0]}')

In [ ]:
print(f'Accuracy on SAMPLE TEST CASES : {classifier3.evaluate(df_testing, output_testing)[1]} \n')
print(f'Loss on SAMPLE TEST CASES : {classifier3.evaluate(df_testing, output_testing)[0]}')

In [ ]:
print(f'Accuracy on SAMPLE TEST CASES : {classifier4.evaluate(df_testing, output_testing)[1]} \n')
print(f'Loss on SAMPLE TEST CASES : {classifier4.evaluate(df_testing, output_testing)[0]}')

In [ ]:
print(f'Accuracy on SAMPLE TEST CASES : {classifier5.evaluate(df_testing, output_testing)[1]} \n')
print(f'Loss on SAMPLE TEST CASES : {classifier5.evaluate(df_testing, output_testing)[0]}')

In [ ]:
print(f'Accuracy on SAMPLE TEST CASES : {classifier6.evaluate(df_testing, output_testing)[1]} \n')
print(f'Loss on SAMPLE TEST CASES : {classifier6.evaluate(df_testing, output_testing)[0]}')

In [ ]:
def sample_case_performance(classifier):
    predicted_values = classifier.predict_classes(df_testing).tolist()
    predicted_values = [i[0] for i in predicted_values]
    _predicted = []
    _target = []
    for i, j in zip(range(0, len(predicted_values), 3), range(0, len(output_testing), 3)):
        _predicted.append(mode(predicted_values[i:i+3]))
        _target.append(mode(output_testing[i:i+3].tolist()))
    correct = 0
    incorrect = 0
    for i, j in zip(_predicted, _target):
        if i == j:
            correct += 1
        else:
            incorrect += 1
    accuracy = correct/(correct + incorrect)
    print(f'Correct predictions : {correct}')
    print(f'Incorrect predictions : {incorrect}')
    print(f'Accuracy : {accuracy*100}')

In [ ]:
sample_case_performance(classifier1)

In [ ]:
sample_case_performance(classifier2)

In [ ]:
sample_case_performance(classifier3)

In [ ]:
sample_case_performance(classifier4)

In [ ]:
sample_case_performance(classifier5)

In [ ]:
sample_case_performance(classifier6)

In [ ]:
#classifier1.save('/Users/rt/Desktop/classifier1.h5')
#classifier2.save('/Users/rt/Desktop/classifier2.h5')
#classifier3.save('/Users/rt/Desktop/classifier3.h5')
#classifier4.save('/Users/rt/Desktop/classifier4.h5')
#classifier5.save('/Users/rt/Desktop/classifier5.h5')
#classifier6.save('/Users/rt/Desktop/classifier6.h5')